![Alt text](https://gistcdn.githack.com/Gbecdox/a45fd09fda68fc656788b7a510ae103d/raw/11f2c6ca24c2f0dd882f98b4ddd1a19a23c7cfd9/HeaderNUM.svg)

Nesse notebook veremos sobre:

* **Criação e atributos de ndarrays**

* **Tópicos de *indexing* e *slicing***

* **Modificação de ndarrays**

* **Operações com uma ou mais ndarrays**

* **Operadores lógicos**

* **Funções randômicas**

* **Funções matemáticas**

# Introdução

## Importando e entendendo o funcionamento

Antes de iniciarmos com as aplicações do pacote, vamos entender o essencial: as principais distinções entre as *arrays* do NumPy e as listas nativas do Python. Para isso, elencamos abaixo algumas diferenças fundamentais.

**No Python, uma lista:**
* pode ser composta por diferentes estruturas de dados, por exemplo, em uma mesma lista podemos ter *strings*, *floats* e inteiros;
* possui tamanho variável, isto é, toda vez que se adicionam ou se removem elementos dela, ela é atualizada.


**No Numpy, uma ndarray:**
* sempre contém uma única estrutura de dados em seu interior, então o pacote sempre irá procurar uma forma de converter todos os dados passados para um mesmo tipo;
* possui tamanho fixo, então quando são adicionados ou removidos elementos de uma ndarray ocorre que, na verdade, ela é deletada e cria-se uma nova, tudo automaticamente.

Além disso, um fator chave da biblioteca é a diversidade de operações matemáticas que ela traz consigo, operações essas que, no Python nativo, muitas vezes teriam que ser implementadas do zero e ainda estariam sob o risco de possuir um maior tempo de execução. Sem mais, vamos começar.

In [1]:
import numpy as np

***
**Observação:** caso você não esteja habituado à nomenclatura, é importante saber que

* ***array*** é, em programação, uma estrutura de dados. Trata-se de um conjunto de elementos que devem ser passíveis de identificação através de um índice ou de uma chave (comumente, é traduzido para o português como "matriz", "vetor" ou "arranjo");

* **ndarray** (*n-dimensional array*) é a classe de *arrays* do NumPy, considerada o objeto principal do pacote.
***

# Criando *arrays* do NumPy

## Com auxílio de estruturas do Python

Muitos são os métodos possíveis para se criar uma ndarray. Começaremos tudo utilizando a função `np.array()`, ela recebe um `array_like`, basicamente, qualquer estrutura de dados que possa ser convertida em uma ndarray (e.g. inteiros, tuplas, listas, dentre outros) e o transforma em uma ndarray. Caso seja do seu interesse, uma definição mais elaborada de um `array_like` pode ser encontrada através do [Stack Overflow](https://stackoverflow.com/questions/40378427/numpy-formal-definition-of-array-like-objects). De qualquer forma, vamos criar e visualizar as variáveis que transformaremos em ndarrays.

In [2]:
L = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # Define L como uma lista.
T = ("a", "b", "c")                 # Define T como uma tupla.
I = 42                              # Define I como um inteiro.

Embora seja dispensável, vamos apenas confirmar se obtivemos o esperado:

In [3]:
print("L (tipo):", type(L)) # Imprime o tipo de L.
print("T (tipo):", type(T)) # Imprime o tipo de T.
print("I (tipo):", type(I)) # Imprime o tipo de I.

L (tipo): <class 'list'>
T (tipo): <class 'tuple'>
I (tipo): <class 'int'>


Tudo certo! Então vamos convertê-las para ndarrays.

In [4]:
L_np = np.array(L) # Converte L para uma array do NumPy, atribui para L_np.
T_np = np.array(T) # Converte T para uma array do NumPy, atribui para T_np.
I_np = np.array(I) # Converte I para uma array do NumPy, atribui para I_np.

Pronto! Assim já temos as *arrays* do Numpy, como podemos averiguar abaixo:

In [5]:
print("L_np (tipo):", type(L_np)) # Imprime o tipo de L_np.
print("T_np (tipo):", type(T_np)) # Imprime o tipo de T_np.
print("I_np (tipo):", type(I_np)) # Imprime o tipo de I_np.

L_np (tipo): <class 'numpy.ndarray'>
T_np (tipo): <class 'numpy.ndarray'>
I_np (tipo): <class 'numpy.ndarray'>


Por último, para fins meramente comparativos, vamos exibir as variáveis antes e após a conversão.

In [6]:
print("L:", L)                   # Imprime L.
print("L_np:", L_np, end="\n\n") # Imprime L_np e pula uma linha.

print("T:", T)                   # Imprime T.
print("T_np:", T_np, end="\n\n") # Imprime T_np e pula uma linha.

print("I:", I)                   # Imprime I.
print("I_np:", I_np)             # Imprime I_np.

L: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
L_np: [ 1  2  3  4  5  6  7  8  9 10]

T: ('a', 'b', 'c')
T_np: ['a' 'b' 'c']

I: 42
I_np: 42


## Diretamente através do NumPy

Se não quisermos utilizar as estruturas de dados do Python para criar ndarrays, é fácil então recorrer a outras funções da biblioteca para realizar isso diretamente, ilustremos algumas:

* `np.arange()`: especificado um intervalo, retorna uma ndarray **unidimensional** com elementos igualmente espaçados no interior dele.
* `np.linspace()`: especificado um intervalo, retorna uma ndarray de variadas dimensões com elementos igualmente espaçados no interior dele.
* `np.zeros()`: especificada uma dimensão, retorna uma ndarray com todos os elementos iguais a 0.
* `np.ones()`: especificada uma dimensão, retorna uma ndarray com todos os elementos iguais a 1.
* `np.full()`: especificada uma dimensão, retorna uma ndarray com todos os elementos iguais a um certo valor.
* `np.empty()`: especificada uma dimensão, retorna uma ndarray com elementos arbitrários, isto é, números essencialmente randômicos.

### np.arange( )

Para começar, vamos nos aprofundar na primeira função citada. Ao usarmos `np.arrange()` definimos os seguintes argumentos:

* `start`: um `scalar` que demarca o início do intervalo — fechado (maior ou igual);
* `stop`: um `scalar` que demarca o final do intervalo — aberto (estritamente menor);
* `step`: passo, o espaçamento entre os elementos do intervalo;
* `dtype`: o tipo (a estrutura de dados) dos elementos da ndarray.

Caso deseje, exemplos para o `scalar` que citamos podem ser vistos experimentando o comando `np.ScalarType` ou, mais uma vez, através do [Stack Overflow](https://stackoverflow.com/questions/21968643/what-is-a-scalar-in-numpy). De qualquer modo, no âmbito desse notebook, estaremos considerando um `scalar` simplesmente como um número do tipo `int` ou `float`, por exemplo. Vamos às aplicações.

In [7]:
print("Exemplo 1:", np.arange(0, 10, 1, int)) # start=0; stop=10; step=1; dtype=int.

Exemplo 1: [0 1 2 3 4 5 6 7 8 9]


Mas é mesmo preciso definir explicitamente todos esses argumentos? Como já deve imaginar, não. Temos por padrão: `start=0`, `step=1` e `dtype` ajustado coerentemente a estrutura de dados dos outros parâmetros. Ora, podemos então simplificar o comando e obter essa mesma saída fazendo:

In [8]:
print("Exemplo 2:", np.arange(10)) # start=0; stop=10; step=1; dtype=type(10).

Exemplo 2: [0 1 2 3 4 5 6 7 8 9]


Variando um pouco os argumentos, temos um terceiro exemplo para ilustrar melhor o comportamento da função. Confira:

In [9]:
print("Exemplo 3:", np.arange(12.0, 24, 2)) # Note que o tipo float se sobressai sobre o tipo int para inferir o dtype.

Exemplo 3: [12. 14. 16. 18. 20. 22.]


### np.linspace( )

A próxima função que abordaremos será a `np.linspace()`. Em relação à função anterior, temos algumas diferenças importantes para ressaltar, que vão além da questão da dimensionalidade. Para facilitar, vamos às divergências:

* `start`: um `array_like` que demarca o início do intervalo — fechado (maior ou igual);
* `stop`: um `array_like` que demarca o final do intervalo — por padrão, fechado (menor ou igual);
* `num`: a quantidade de elementos no interior do intervalo;
* `endpoint`: quando `True` (*default*) inclui o valor de `stop` no intervalo, quando `False`, não o inclui;
* `retstep`: quando `True`, retorna também o passo dos valores do intervalo, quando `False` (*default*), não.

Retomando os exemplos, vamos primeiro fazer uma construção passando inteiros para `start` e `stop`.

In [10]:
print("Exemplo 4:", np.linspace(0, 10, 11)) # start=0; stop=10; num=11; endpoint=True; retstep=False; dtype=float.

Exemplo 4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Se quisermos ndarrays com duas dimensões (matrizes), por exemplo, podemos então passar listas (sempre de tamanhos iguais) para `start` e `stop`.

In [11]:
# start=[1, 2, 3, 4]; stop=[1, 8, 27, 64]; num=4; endpoint=True; retstep=False; dtype=int.
print("Exemplo 5:", np.linspace([1, 2, 3, 4], [1, 8, 27, 64], 4, dtype=int), sep="\n")

Exemplo 5:
[[ 1  2  3  4]
 [ 1  4 11 24]
 [ 1  6 19 44]
 [ 1  8 27 64]]


Por fim, ao usarmos `retstep=True` a função retornará uma tupla de dois elementos, tais que: o primeiro (de índice 0) é a ndarray desejada e o segundo (de índice 1) é o passo dos elementos da ndarray. Vejamos:

In [12]:
A = np.linspace(0, 10, 10, endpoint=False, retstep=True) # Cria A, uma tupla que contém a ndarray e o passo.

print("Exemplo 6:", A, end="\n\n") # Imprime A e pula uma linha.

print("Ndarray:", A[0]) # Imprime a ndarray.
print("Passo:", A[1])   # Imprime o passo.

Exemplo 6: (array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

Ndarray: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Passo: 1.0


### np.zeros( ), np.ones( ) e np.full( )

Para as próximas três funções: `np.zeros()`, `np.ones()` e `np.full()`, teremos um funcionamento semelhante. Na verdade, como somente um mesmo elemento irá compor cada uma das ndarrays, apenas precisaremos definir

* `shape`: a dimensão da ndarray, para as três funções;
* `fill_value`: o elemento que irá compor ndarray, para a `np.full()`.

Quanto à dimensão, podemos passar como argumento para `shape` um inteiro e obter uma ndarray unidimensional, ou então uma tupla e teremos uma ndarray com mais dimensões. Vamos demonstrar tudo isso com mais alguns exemplos.

In [13]:
print("Exemplo 7:", np.zeros(7, int)) # shape=7 (unidimensional); dtype=int.

Exemplo 7: [0 0 0 0 0 0 0]


In [14]:
print("Exemplo 8:", np.ones((3,3)), sep="\n") # shape=(3,3) (bidimensional); dtype=float.

Exemplo 8:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
print("Exemplo 9:", np.full((4,5), 6), sep="\n") # shape=(4,5) (bidimensional); fill_value=6; dtype=type(6).

Exemplo 9:
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


### np.empty( )

Antes de continuarmos com a `np.empty()` talvez seja interessante entender melhor um conceito que abordamos há pouco, quando a função foi apresentada. Lá, citamos a expressão "números arbitrários" querendo nos referir a números que fossem de fato aleatórios, isto é, tomados ao acaso. Por outros termos, pretendiamos dizer que a `np.empty()` não gerou esses valores para compor a ndarray, a grosso modo, podemos pensar que "já havia valores na memória do computador e a ndarray foi apenas ali alocada".

Uma diferença importante desse processo para aquele cujas as funções ditas randômicas (tais quais as da biblioteca `random` do Python) fazem, é o tempo de execução. A exemplo, ao aplicar uma função como `random.randrange()` estamos gerando **pseudo-random numbers**: números obtidos através de uma construção matemática que busca simular a aleatoriedade. Pois então, é evidente que esse processo deva consumir um maior tempo, haja vista a necessidade de se realizarem todos os cálculos.

Assim, embora a ndarray criada com a `np.empty()` possua valores que, muito provavelmente, não serão do nosso interesse e, portanto, precisaremos substitui-los, temos a vantagem reduzir o tempo de sua criação — em especial, quando estamos trabalhando com grandes dimensões.

In [16]:
# Usando np.empty(), imprime uma matriz 3x3.
print("Exemplo 10:", np.empty((3,3)), sep="\n")

# Define uma matriz 3x3 qualquer, sem imprimi-la ou atribui-la a uma variável.
np.array([[9., 8., 7.], 
          [6., 5., 4.], 
          [3., 2., 1.]])

# Usando np.empty(), imprime uma matriz 3x3.
print("\nExemplo 11:", np.empty((3,3)), sep="\n")

Exemplo 10:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Exemplo 11:
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


Nos casos a cima, perceba que obtivemos saídas diferentes apenas definindo uma nova matriz quadrada de ordem 3, ainda que sem atribui-la a alguma variável. No **Exemplo 10** temos uma cópia do **Exemplo 8**; no **11**, uma outra matriz. Eis então uma demonstração da função `np.empty()` apenas "utilizar o que já está pronto".

***
**Aviso:** executar as células em uma ordem que não seja a esperada (da primeira para a última) poderá alterar as saídas dos dois exemplos.
***

# Atributos de uma ndarray

Tal qual uma lista nativa do Python possui, por exemplo, um tamanho; as ndarrays também contam com atributos que as definem, a saber

* `ndarray.ndim`: o número de dimensões (**eixos** ou ***axis***, no inglês) de uma ndarray.
* `ndarray.shape`: o tamanho das dimensões, uma tupla de inteiros que indica o tamanho da ndarray em cada eixo.
* `ndarray.size`: o número total de elementos de uma ndarray.
* `ndarray.dtype`: o tipo (a estrutura de dados) dos elementos que compõem uma ndarray.
* `ndarray.itemsize`: o tamanho dos elementos de uma ndarray em **bytes**.

Para verificar cada um desses atributos, vamos antes definir uma matriz **B**:

In [17]:
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Agora, em ordem, trabalharemos cada um deles e algumas de suas particularidades.

### ndarray.ndim

In [18]:
print("Número de dimensões de B:", B.ndim)

Número de dimensões de B: 2


### ndarray.shape

In [19]:
print("Tamanho das dimensões de B:", B.shape)

Tamanho das dimensões de B: (3, 3)


Ora, quando utilizamos `B.shape` descobrimos que os tamanhos de **B** no **eixo 0** e no **eixo 1** é 3. Mas também estamos, implicitamente, inferindo que **B** possui duas dimensões (dois eixos), isso nos permite uma nova construção que torna o uso de `B.ndim` prescindível. Observe:

In [20]:
print("Número de dimensões de B:", len(B.shape))

Número de dimensões de B: 2


**Em síntese:** a quantidade de inteiros na tupla é igual ao número de dimensões e os inteiros nela presentes, os tamanhos de cada dimensão.

### ndarray.size

In [21]:
print("Total de elementos de B:", B.size)

Total de elementos de B: 9


Podemos notar aqui uma outra relação existente entre os atributos e que também envole `B.shape`. O número total de elementos em uma ndarray é, na verdade, o produto dos tamanhos das dimensões (ou como acabamos de dizer, o produto dos inteiros que compõem a tupla `B.shape`).

In [22]:
print("Total de elementos de B:", B.shape[0] * B.shape[1])

Total de elementos de B: 9


### ndarray.dtype

In [23]:
print("Tipo (estrutura de dados) dos elementos de B:", B.dtype)

Tipo (estrutura de dados) dos elementos de B: int32


### ndarray.itemsize

In [24]:
print("Tamanho dos elemento de B:", B.itemsize, "bytes")

Tamanho dos elemento de B: 4 bytes


Duas observações pertinentes a respeito de `B.itemsize`:

* é devolvido apenas o valor numérico (**4**, nesse caso) e
* 1 byte é equivalente a 8 bits, ou seja, a estrutura `int32` possui 4 bytes (32 bits).

# *Indexing* e *slicing*

Agora que já foi abordado o conceito de dimensão, trabalharemos com mais um item imprescindível de qualquer *array*: os índices. Vamos nos centrar em algumas técnicas que permitem obter tanto um elemento específico de uma ndarray, quanto um segmento (uma "fatia") dessa por meio de índices.

## *Basic Indexing*

Com o uso do NumPy podemos fazer a indexação básica (mais à frente a diferenciaremos melhor) por meio de alguns modos, sendo do nosso interesse focar em dois mais usuais:

* analogamente ao que já conhecemos do Python, quanto à indexação de listas e tuplas, por exemplo;
* próprio do NumPy, no qual os índices a serem acessados devem todos estar dentro de um mesmo par de colchetes e serem, entre si, separados por vírgula.

Para exemplificar, definiremos **D1** e **D2**, ndarrays de diferentes dimensões.

In [25]:
# Define D1: uma ndarray unidimensional.
D1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define D2: uma ndarray bidimensional.
D2 = np.array([[1., 2., 3.],
               [4., 5., 6.],
               [7., 8., 9.]])

Relembrando, temos abaixo uma guia que ilustra como é feita a leitura de índices no Python em ambos os sentidos: da esquerda para direita (convencional) ou da direita para esquerda. É importante perceber que, na leitura convencional, o primeiro elemento possui índice 0; o segundo, índice 1; o terceiro, índice 2 e assim sucessivamente.

<img style="float: left;" src=https://i.ibb.co/Fbh4JSc/D1.png, width=340>

Como **D1** é uma ndarray unidimensional, temos, no nosso caso, apenas uma alternativa para indexação:

In [26]:
print("Primeiro elemento de D1:", D1[0]) # Análogo ao Python
print("Último elemento de D1:", D1[-1])  # Análogo ao Python

Primeiro elemento de D1: 1
Último elemento de D1: 9


Contudo, para **D2** ambos os modos citados anteriormente são possíveis:

In [27]:
print("Primeira linha e primeira coluna de D2:", D2[0][0]) # Análogo ao Python
print("Primeira linha e terceira coluna de D2:", D2[0,2])  # Próprio do NumPy

Primeira linha e primeira coluna de D2: 1.0
Primeira linha e terceira coluna de D2: 3.0


Ainda que os resultados sejam equivalentes, utilizar as vírgulas é preferível, pois torna a escrita mais econômica e a leitura mais clara, haja vista que para uma grande quantidade de dimensões o uso de colchetes pode se tornar excessivo.

***
**Importante:** tanto `D2[0,2]` quanto `D2[(0,2)]` possuem saídas iguais. Não consideramos esse último um terceiro método pois, na verdade, o NumPy cria uma tupla com as informações no interior dos colchetes sempre que necessário. Além disso, são **os tipos dos dados no interior dessa tupla** os responsáveis pela distinção entre *basic indexing* e *advanced indexing*. Se julgar necessário, é possível se [aprofundar](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/BasicIndexing.html). 
***

## *Advanced Indexing*

Trataremos somente um caso (de grande relevância) da indexação avançada, trata-se do uso de **expressões booleanas**. Basicamente, enquanto na indexação básica usavamos, por exemplo, os inteiros dentro dos colchetes, agora estaremos utilizando uma comparação que nos retorna `True` ou `False`. A vantagem disso é que tal artifício nos permite, por exemplo, "filtrar" valores de uma ndarray: teremos como retorno somente os elementos que satisfaçam a condição imposta. Observe:

In [28]:
print("Elementos de D1 maiores do que 5:", D1[D1 > 5])
print("Elementos de D1 menores do que 3:", D1[D1 < 3])

Elementos de D1 maiores do que 5: [6 7 8 9]
Elementos de D1 menores do que 3: [1 2]


Obviamente, podemos utilizar nessas comparações quaisquer que sejam os operadores relacionais (`==`, `!=`, `>`, `>=`, `<` e `<=`), inclusive, com ndarrays de mais dimensões:

In [29]:
print("Elementos de D2 maiores ou iguais a 6:", D2[D2 >= 6])
print("Elementos de D2 diferentes de 2:", D2[D2 != 2])

Elementos de D2 maiores ou iguais a 6: [6. 7. 8. 9.]
Elementos de D2 diferentes de 2: [1. 3. 4. 5. 6. 7. 8. 9.]


## *Slicing*

Para realizar os cortes seguiremos o caminho análogo ao do Python: no interior de um par de colchetes teremos inteiros separados pelo sinal de dois pontos. Melhor explicando, podemos afirmar que a notação será da forma `[start:stop:step]`, na qual:

* `start` é o índice que determina o início do corte, inclui-se o elemento de índice `start` no corte;
* `stop` é o índice que determina o final do corte, exclui-se o elemento de índice `stop` no corte;
* `step` é o passo dos índices.

Aliás, é importante saber que o *default* para cada um dos parâmetros é:

* `start=0`, o primeiro elemento da ndarray;
* `stop=n`, sendo `n` o número de elementos na dimensão cortada da ndarray;
* `step=1`, evitando "pular" algum elemento.

Ainda, é interessante notar que se todos os três parâmetros possuem um valor pré-definido, podemos então omiti-los sem incorrer em um erro de sintaxe. Vejamos:

In [30]:
print("D1:", D1[:]) # start=0; stop=9; step=1; a expressão D1[::] é válida e equivalente.

D1: [1 2 3 4 5 6 7 8 9]


Vamos agora ver alguns outros casos para **D1** que, no geral, não se distanciam daquilo que já conhecemos.

In [31]:
print("Do 2º ao 4º elemento de D1:", D1[1:4])              # start=1; stop=4; step=1
print("Do 1º ao 8º elemento de D1:", D1[:8])               # start=0; stop=8; step=1
print("Do 3º ao 9º elemento de D1 com passo 2:", D1[2::2]) # start=2; stop=9; step=2

Do 2º ao 4º elemento de D1: [2 3 4]
Do 1º ao 8º elemento de D1: [1 2 3 4 5 6 7 8]
Do 3º ao 9º elemento de D1 com passo 2: [3 5 7 9]


Como deve ter notado com os exemplos, quando utilizamos dentro dos colchetes somente um único sinal de `:` será feita a leitura de um valor para `start` e doutro para `stop`, sendo apenas possível alterar o valor de `step` se utilizarmos um segundo `:`. Por último, tome cuidado ao definir o passo quando estiver utilizando índices negativos, pois esse também deverá ser menor do que zero para se percorrer a ndarray no sentido não convencional.

In [32]:
print("Do 8º ao 1º elemento:", D1[-2:-10:-1]) # Equivalentemente: D1[-2::-1].

Do 8º ao 1º elemento: [8 7 6 5 4 3 2 1]


Trabalhando agora as ndarrays com mais eixos, teremos o *slicing* sem grandes novidades, basta apenas separar com uma vírgula o corte em cada uma das dimensões. Com o auxílio da guia abaixo, na qual temos **D2** e seus dois eixos (**0:** linhas; **1:** colunas), retomaremos os exemplos.

<img style="float: left;" src=https://i.ibb.co/QHB54S2/D2.png, width=300>

In [33]:
print("Segunda linha de D2:", D2[1:2,:]) # No eixo 0 (linhas): start=1; stop=2; step=1 # No eixo 1 (colunas): start=0; stop=3; step=1

Segunda linha de D2: [[4. 5. 6.]]


Na construção a cima, indicamos o corte no **eixo 0** com `1:2` e, após a vírgula, o corte no **eixo 1** através de `:`. Mas, nesse caso, podemos ser ainda mais econômicos: basta apenas escrever `D2[1:2]`. Por outros termos, quando omitimos o corte em uma dimensão, pressupõe-se que queremos exibi-la por inteiro.

In [34]:
print("Dois últimos elementos da última coluna de D2:", D2[1:,2:], sep="\n") # Equivalentemente: D2[1:3:1,2:3:1].

Dois últimos elementos da última coluna de D2:
[[6.]
 [9.]]


In [35]:
print("Menor submatriz quadrada de ordem 2 em D2:", D2[:2,:2], sep="\n") # Equivalentemente: D2[0:2:1,0:2:1].

Menor submatriz quadrada de ordem 2 em D2:
[[1. 2.]
 [4. 5.]]


# Modificando *arrays* do NumPy

Obviamente não precisamos criar uma ndarray da forma como a usaremos, inclusive, podemos fazer algumas modificações por meio de *indexing* e *slicing*, como vimos. Mas agora vamos empregar algumas funções do NumPy destinadas, justamente, a realizar alterações em ndarrays.

## Remodelando

Começaremos por `np.reshape()`, para essa função passaremos dois argumentos: (1) uma ndarray e (2) as dimensões desejadas para ela. Ao final, teremos como retorno uma cópia da ndarray inicial após ser "remodelada". Para exemplificar, vamos recriar nossa matriz **B**:

In [36]:
b = np.arange(1, 10)     # Define b: uma ndarray unidimensional com inteiros do 1 ao 10 (não incluído) e passo 1
B = np.reshape(b, (3,3)) # Define B: reorganização de b como uma matriz quadrada de ordem 3 (ndarray bidimensional).

Já trabalhamos isso com maior cautela, mas novamente: repare que através da tupla passamos duas informações, isto é

* o número de dimensões (a quantidade de elementos na tupla — seu comprimento) e
* o tamanho das dimensões (os inteiros que compõem a tupla).

Apenas não se esqueça de tomar cuidado para garantir que o número de elementos permaneça igual antes e depois da transformação. Por último, lembre-se de que para eventuais dúvidas a [documentação](https://numpy.org/doc/1.17/reference/generated/numpy.reshape.html) pode ajudar.

In [37]:
print(B) # Visualização da matriz que acabamos de recriar.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Podemos também querer fazer o procedimento inverso, isto é, se por algum acaso quisermos transformar uma ndarray qualquer em uma ndarray unidimensional utilizamos a `np.reshape()`, como vemos no exemplo abaixo, no qual imprimimos a matriz **B** "planificada" (equivalente à **b**).

In [38]:
print(np.reshape(B, (9,))) # Impressão de B em uma forma unidimensional.

[1 2 3 4 5 6 7 8 9]


Felizmente, essa não é a nossa única alternativa. Tanto a função `np.ravel()`, quanto o método `ndarray.flatten()` podem ser utilizados para o que desejamos. Contudo, existem diferenças importantes que, para serem compreendidas, precisaremos antes ter uma noção básica sobre como são feitas as cópias de ndarrays. Para tal, vamos considerar a existência de dois caminhos possíveis:

> **1.** A cópia gerada é, na verdade, uma visualização da versão original, ou seja, ambas estão "interligadas". Dessa forma, modificar uma **também** irá alterar a outra.

> **2.** A cópia gerada e a versão original são independentes. Dessa forma, modificar uma **não** irá alterar a outra.

Portanto, temos a `np.ravel()` e, sempre que possível, a `np.reshape()`, operando da primeira forma, enquanto `ndarray.flatten()` opera conforme a segunda. Vamos esclarecer essa diferença abaixo, tratando os dois casos.

**Caso 1:** utilizando a `np.ravel()` verificaremos que mudanças na cópia alteram **também** a ndarray original (e vice-versa).

In [39]:
# Define uma matriz quadrada de ordem 2 com os inteiros 1, 2, 3 e 4
matriz_1 = np.array([[1, 2],
                     [3, 4]])

# Define uma cópia unidimensional de matriz_1 através de np.ravel().
copia_1 = np.ravel(matriz_1)
# Altera o primeiro elemento de copia_1 para 7
copia_1[0] = 7

print(matriz_1) # Imprime matriz_1.

[[7 2]
 [3 4]]


Como foi dito, embora a mudança tenha sido feita na variável `copia_1`, a variável `matriz_1` também foi modificada (de fato, temos dois ponteiros que indicam um mesmo lugar na memória). Vale ressaltar que substituindo `np.ravel(matriz_1)` por `np.reshape(matriz_1, (4,))` teríamos esse mesmo resultado.

**Caso 2:** utilizando `ndarray.flatten()` verificaremos que mudanças na cópia **não** alteram a ndarray original (e vice-versa).

In [40]:
# Define uma matriz quadrada de ordem 2 com os inteiros 1, 2, 3 e 4
matriz_2 = np.array([[1, 2],
                     [3, 4]])

# Define uma cópia unidimensional de matriz_2 através de ndarray.flatten().
copia_2 = matriz_2.flatten()
# Altera o primeiro elemento de copia_2 para 7
copia_2[0] = 7

print(matriz_2) # Imprime matriz_2.

[[1 2]
 [3 4]]


Tal qual esperávamos, `matriz_2` permaneceu inalterada, enquanto `copia_2` sofreu de fato a alteração, verifique:

In [41]:
print(copia_2)

[7 2 3 4]


***
**Importante:** agora que já sabemos disso, é útil incluir mais algumas informações.

* Comumente, diz-se que a primeira forma retorna uma *view* da ndarray de entrada, enquanto a segunda, uma *copy*.
* `np.copy()` possui justamente a função de criar uma cópia (como da segunda forma) de uma ndarray.

Quanto às técnicas de indexação e corte que vimos, acrescentamos:

* *basic indexing* e *slicing* retornam uma *view* (como da primeira forma);
* qualquer técnica de *advanced indexing* sempre retorna uma *copy* (como da segunda forma).
***

## Acrescentando e removendo

Vamos agora ver três funções que nos permitem inserir e detelar elementos (números, se unidimensional; linhas ou colunas, se bidimensional) de uma ndarray.

* `np.append()`: insere um elemento no final de uma ndarray;
* `np.insert()`: insere um elemento numa determinada posição de uma ndarray;
* `np.delete()`: remove um elemento de uma ndarray.

Usaremos nos exemplos outras duas ndarrays, uma unidimensional (**N1**) e outra bidimensional (**N2**), ambas criadas abaixo.

In [42]:
# Ndarray unidimensional com cinco inteiros (do 0 ao 4).
N1 = np.arange(5)

# Ndarray bidimensional.
N2 = np.array([[7, 2],
               [1, 5]])

Pronto, vamos apenas visualizar as ndarrays criadas.

In [43]:
print(N1) # Visualização da matriz que acabamos de criar.

[0 1 2 3 4]


In [44]:
print(N2) # Visualização da matriz que acabamos de criar.

[[7 2]
 [1 5]]


***
**Observação:** as três funções citadas, na verdade, conseguem atuar sobre qualquer `array_like`, não somente sobre uma ndarray.
***

### np.append( )

Para `np.append()` vamos primeiro trabalhar o caso unidimensional. Destarte, precisaremos (1) indicar em qual ndarray será feita a inserção e (2) passar os elementos que queremos acrescentar.

In [45]:
print("Exemplo 12:", np.append(N1, 5))      # Insere o inteiro 5 no final de N1.
print("Exemplo 13:", np.append(N1, [5, 6])) # Insere a lista [5, 6] no final de N1.

Exemplo 12: [0 1 2 3 4 5]
Exemplo 13: [0 1 2 3 4 5 6]


Agora, considerando mais dimensões, a função opera com algumas diferenças. Basicamente, se não especificarmos o parâmetro `axis` a nossa saída será uma ndarray unidemsional, independentemente dos dados de entrada. Veja:

In [46]:
print("Exemplo 14:", np.append(N2, 8))  # "Planifica" a ndarray N2 e insere o inteiro 8 em seu final.
print("Exemplo 15:", np.append(N2, N2)) # "Planifica" a ndarray N2 e insere uma "planificação" de N2 no seu final.

Exemplo 14: [7 2 1 5 8]
Exemplo 15: [7 2 1 5 7 2 1 5]


Por outros termos, podemos dizer que, ao omitir o parâmetro `axis`, todos os dados de entrada serão convertidos para ndarrays unidimensionais e só então concatenados. Como essa perda de informação geralmente não é o que procuramos, deve-se:

* definir em qual eixo/dimensão (linhas ou colunas) deverá ser feita a inserção;
* assegurar que, nessa dimensão, as filas possuam tamanhos iguais.

**Exemplo:** a matriz **N2** possui duas linhas e duas colunas. Para acrescentar mais colunas a ela precisaremos definir `axis=1` (isto é, indicar que a inserção é para ser feita no eixo das colunas) e apenas inserir colunas com duas linhas, pois esse é o número de linhas de **N2**.

In [47]:
print("Exemplo 16:", np.append(N2, N2, axis=1), sep="\n") # Concatena N2 à direita de N2.

Exemplo 16:
[[7 2 7 2]
 [1 5 1 5]]


In [48]:
print("Exemplo 17:", np.append(N2, [[3, 6]], axis=0), sep="\n") # Concatena [[3, 6]] (matriz linha) embaixo de N2.

Exemplo 17:
[[7 2]
 [1 5]
 [3 6]]


### np.insert( )

Com `np.insert()` teremos um procedimento parecido, inclusive quanto à especificação ou não do eixo. Todavia, temos agora a possibilidade de introduzir os elementos em um ponto qualquer da ndarray, não somente no final, como ocorria com `np.append()`. Novamente, vamos primeiro nos voltar ao caso unidimensional.

In [49]:
print("Exemplo 18:", np.insert(N1, 3, 5)) # Insere em N1, no índice 3, o número 5

Exemplo 18: [0 1 2 5 3 4]


Observe então que a ordem dos argumentos deve ser a seguinte:

* ndarray na qual será feita a inserção;
* índice que deverá ser ocupado pelo elemento a ser inserido;
* o elemento a ser inserido.

Por último, para duas ou mais dimensões, indicamos o eixo com `axis`.

In [50]:
# Insere [[9, 4]] (matriz linha) em N2, como uma linha (axis=0) de índice 1.
print("Exemplo 19:", np.insert(N2, 1, [[9, 4]], axis=0), sep="\n")

Exemplo 19:
[[7 2]
 [9 4]
 [1 5]]


**Vale relembrar:** omitr `axis` também implicará uma "planificação" dos elementos e ainda precisamos estar atentos às dimensões.

### np.delete( )

Como citamos, com a função `np.delete()` poderemos excluir elementos de ndarrays. Mas tomemos cuidado: para duas dimensões, estaremos removendo sempre uma linha ou uma coluna por completo. Além disso, a remoção ocorre por meio do uso de índices, veja os argumentos:

* a ndarray que terá um elemento removido;
* os índices dos elementos a serem removidos;
* o eixo no qual deve ocorrer a remoção (se possuir mais de uma dimensão).

Inicialmente, vamos ver o exemplo para **N1**:

In [51]:
print("Exemplo 20:", np.delete(N1, 2)) # Remove o terceiro elemento (índice 2) de N1.

Exemplo 20: [0 1 3 4]


Para **N2**, basta então que especifiquemos o eixo, para evitar a "planificação".

In [52]:
print("Exemplo 21:", np.delete(N2, 0, axis=1), sep="\n") # Remove a primeira (índice 0) coluna (axis=1) de N2.

Exemplo 21:
[[2]
 [5]]


## Reordenando

### np.sort( )

Por último, `np.sort()` irá organizar os elementos no interior de uma ndarray em ordem crescente (por padrão). No nosso caso, os elementos de **N1** já se encontram dessa forma, podemos então colocá-los em ordem decrescente. Fazemos isso de uma forma pouco usual: insere-se um sinal de menos antes da função e outro dentro dos parêntesis, antes da ndarray. Isto é:

* `np.sort(N1)` organiza **N1** em ordem crescente;
* `-np.sort(-N1)` organiza **N1** em ordem decrescente.

In [53]:
print("Exemplo 22:", -np.sort(-N1)) # Organiza N1 em ordem decrescente.

Exemplo 22: [4 3 2 1 0]


Já para **N2** precisaremos de maior cautela, a função `np.sort()` irá organizar em ordem crescente: as linhas, se `axis=0`; as colunas, se `axis=1`. Enquanto para `axis=None` teremos uma "planificação" da ndarray ordenada crescentemente.

In [54]:
print("Exemplo 23:", np.sort(N2, axis=0), sep="\n") # Organiza as linhas de N2 em ordem crescente.

Exemplo 23:
[[1 2]
 [7 5]]


In [55]:
print("Exemplo 24:", np.sort(N2, axis=1), sep="\n") # Organiza as colunas de N2 em ordem crescente.

Exemplo 24:
[[2 7]
 [1 5]]


Agora, vamos verificar `axis=None`.

In [56]:
print("Exemplo 25:", np.sort(N2, axis=None), sep="\n") # Planifica N2 e organiza seus elementos em ordem crescente.

Exemplo 25:
[1 2 5 7]


Diferentemente das outras funções que abordamos nessa seção, `np.sort()` possui como *default* `axis=-1` e **não** `axis=None`. Desse modo, escolhe-se sempre a última dimensão quando omitimos tal argumento.

# Métodos e operações com uma ndarray

Inicialmente, continuaremos a coletar informações sobre as ndarrays, mas agora já com um maior apelo matemático para, finalmente, começarmos com algumas operações. Tudo isso será feito ainda nos atendo a uma única ndarray, nossa matriz **B**.

## Métodos

Antes de começar, caso precise, fique com um lembrete da matriz **B**:

In [57]:
print(B) # Imprime B.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### ndarray.max( ) e ndarray.min( )

Análogos às funções `max()` e `min()` do Python, os métodos `ndarray.max()` e `ndarray.min()` retornam, respectivamente, o maior e o menor elemento em uma ndarray. Logo:

In [58]:
print("Maior elemento de B:", B.max())
print("Menor elemento de B:", B.min())     

Maior elemento de B: 9
Menor elemento de B: 1


Mas uma diferença interessante se encontra no argumento `axis`. Quando passado, a operação ocorrerá levando em conta somente aquela dimensão (eixo). Por exemplo, no caso de uma matriz, `ndarray.max(axis=0)` implicará uma busca pela linha cujos elementos quando somados resultem no maior valor possível, retornando justamente essa tal linha.

In [59]:
print("Maior linha de B:", B.max(axis=0))  # axis=0 (linha).
print("Menor coluna de B:", B.min(axis=1)) # axis=1 (coluna).

Maior linha de B: [7 8 9]
Menor coluna de B: [1 4 7]


***
**Observação:** "maior linha" e "menor coluna" querem dizer "linha com maior soma" e "coluna com menor soma", respectivamente.
***

### ndarray.sum( ) e ndarray.cumsum( )

Como os nomes sugerem, `ndarray.sum()` e `ndarray.cumsum()` retornam, respectivamente, a soma e a soma cumulativa de uma ndarray. Caso não saiba, a soma cumulativa pode ser simplificadamente definida como uma sequência de somas parciais: o resultado da soma dos valores conforme se adiciona valor a valor.

In [60]:
print("Soma dos elementos de B:", B.sum())
print("Soma cumulativa de B:", B.cumsum()) 

Soma dos elementos de B: 45
Soma cumulativa de B: [ 1  3  6 10 15 21 28 36 45]


Assim como anteriormente, podemos definir o argumento `axis` e condicionaremos a operação a uma dimensão específica, isto é:

In [61]:
print("Soma dos elementos para cada linha de B:", B.sum(axis=1))

Soma dos elementos para cada linha de B: [ 6 15 24]


Aparentemente, poderiamos considerar a construção a cima adversa, afinal utilizamos `axis=1` para obter uma soma com referência nas linhas da matriz, ainda que o **eixo 1** designe colunas. Contudo, notemos que, fixada uma linha, somar seus elementos é, na verdade, somar as colunas (e vice-versa). Em síntese, trata-se apenas de uma construção gramaticalmente distinta, mas com igual valor.

In [62]:
print("Soma cumulativa das colunas de B:", B.cumsum(axis=1), sep="\n")

Soma cumulativa das colunas de B:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


### ndarray.prod( ) e ndarray.cumprod( )

Ao invés de trabalharmos com a soma e a soma cumulativa, podemos desejar o produto e o produto cumulativo, respectivamente, `ndarray.prod()` e `ndarray.cumprod()`. A aplicação e o funcionamento são próximos do que já vimos. Observe:

In [63]:
print("Produto das linhas de B:", B.prod(axis=0))
print("Produto cumulativo de B:", B.cumprod())

Produto das linhas de B: [ 28  80 162]
Produto cumulativo de B: [     1      2      6     24    120    720   5040  40320 362880]


## Operações

Finalmente, vamos começar a trabalhar com operações entre números e ndarrays, o principal ponto é compreender que estamos falando de operações do tipo **elementwise**, ou seja, que serão aplicadas a cada um dos elementos da ndarray. A exemplo, somar 5 a uma ndarray é, essencialmente, somar 5 a cada um de seus elementos.

### Operadores aritméticos

Como já citamos no exemplo a cima, aplicar qualquer um deles (`+`, `-`, `*`, `**`, `/`, `//` e `%`) entre uma ndarray e um número irá resultar em uma nova ndarray, essa, contendo os resultados das contas para cada elemento.

In [64]:
print(B + 5.0)

[[ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]


In [65]:
print(B - 5)

[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]


In [66]:
print(B * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [67]:
print(B ** 2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [68]:
print(B / 10)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [69]:
print(B // 2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [70]:
print(B % 2)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


### Operadores relacionais

Para os relacionais (`==`, `!=`, `>`, `>=`, `<` e `<=`) teremos um princípio de funcionamento análogo. Contudo, como esperamos, na nossa ndarray resultante estarão presentes somente os valores `True` e `False`, onde esses forem cabíveis.

In [71]:
print(B == 5)

[[False False False]
 [False  True False]
 [False False False]]


In [72]:
print(B != 9)

[[ True  True  True]
 [ True  True  True]
 [ True  True False]]


In [73]:
print(B > 0)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [74]:
print(B >= 3.5)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [75]:
print(B < 0)

[[False False False]
 [False False False]
 [False False False]]


In [76]:
print(B <= 7)

[[ True  True  True]
 [ True  True  True]
 [ True False False]]


### Outras operações (matrizes)

Se quisermos nos especificar mais, é simples obter propriedades típicas das matrizes, nesse caso:

* o **traço** (a soma de todos os elementos da diagonal principal), através de `np.trace()`;
* a matriz **transposta**, através de `ndarray.T`;
* o **determinante**, através de `np.linalg.det()`.

Perceba que, para o determinante, precisamos utilizar um módulo específico do NumPy: `numpy.linalg`. Não nos aprofundaremos nele, mas trata-se de uma excelente alternativa para se trabalhar com tópicos de [álgebra linear](https://numpy.org/doc/1.17/reference/routines.linalg.html). De qualquer forma, vamos primeiro ao traço:

In [77]:
print("Soma dos elementos da diagonal principal de B (traço):", np.trace(B))

Soma dos elementos da diagonal principal de B (traço): 15


E depois, transpor **B**:

In [78]:
print("B transposta:", B.T, sep="\n")

B transposta:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Para o determinante, vamos apenas arredondar o resultado para evitar o ruído, assim:

In [79]:
print("Determinante de B:", round(np.linalg.det(B))) # round() arredonda np.linalg.det(B) para a primeira casa decimal.

Determinante de B: 0.0


# Operações entre múltiplas ndarrays

Uma das maiores vantagens do NumPy é, sem dúvida, a facilidade que possuímos para realizar contas com as ndarrays. Primeiro, vamos no ater aos operadores aritméticos, é importante saber que todas as operações pedidas (uma soma ou uma subtração, por exemplo) serão feitas com os elementos de iguais índices entre as ndarrays. Para que fique mais claro, trabalharemos com alguns exemplos logo após criarmos a nossa nova matriz:

In [80]:
C = np.eye(3) # Define C: matriz identidade de ordem 3 (ndarray bidimensional).

A função `np.eye()` não foi introduzida na seção de criação de ndarrays pois se trata de um caso bem específico: ela retorna a matriz identidade de ordem `N`, sendo `N` um inteiro não negativo (no nosso caso, `N=3`). A [documentação](https://numpy.org/doc/1.17/reference/generated/numpy.eye.html) sem dúvidas pode ajudar, tendo em vista que a função possui suas particularidades. 

In [81]:
print(C) # Visualização da matriz que acabamos de criar.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Operadores aritméticos

Finalmente, para os exemplos, vamos abordar todos os casos anteriores (`+`, `-`, `*`, `**`, `/`, `//` e `%`).

In [82]:
print(B + C)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [83]:
print(B - C)

[[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]


In [84]:
print(B * C)

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


In [85]:
print(B ** C)

[[1. 1. 1.]
 [1. 5. 1.]
 [1. 1. 9.]]


In [86]:
print(C / B) # Observe que (B / C) implicaria uma divisão por zero.

[[1.         0.         0.        ]
 [0.         0.2        0.        ]
 [0.         0.         0.11111111]]


In [87]:
print(C // B) # Observe que (B // C) implicaria uma divisão por zero.

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [88]:
print(C % B) # Observe que (B % C) implicaria uma divisão por zero.

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Como deve ter reparado, a expressão `B * C` seguiu o esperado: a ndarray resultante foi composta pelo produto dos elementos de índices comuns entre **B** e **C**. Mas já que estamos trabalhando com matrizes, poderiamos querer, justamente, o **produto matricial**, com esse objetivo é que utilizamos o operador `@`. Veja:

In [89]:
print(B @ C) # Uma forma equivalente (mas antiga) dessa expressão é B.dot(C).

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Operadores relacionais

Para os operadores relacionais, teremos um funcionamento análogo: será feita a comparação desejada (`==`, `!=`, `>`, `>=`, `<` e `<=`) entre os elementos de iguais índidces das ndarrays e retornada uma terceira composta por `True` e `False`, onde quer que esses sejam aplicáveis.

In [90]:
print(B == C)

[[ True False False]
 [False False False]
 [False False False]]


In [91]:
print(B != C)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [92]:
print(B > C)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [93]:
print(B >= C)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [94]:
print(B < C)

[[False False False]
 [False False False]
 [False False False]]


In [95]:
print(B <= C)

[[ True False False]
 [False False False]
 [False False False]]


# Operadores Lógicos

Para cada operador lógico nativo do Python (`and`, `or`, `not` e `xor`) o NumPy introduz um equivalente, veja:

* `np.logical_and()` retorna `True` se as duas afirmações forem verdadeiras;
* `np.logical_or()` retorna `True` se pelo menos uma das afirmações for verdadeira;
* `np.logical_not()` inverte valores, retorna `True` se a saída for falsa;
* `np.logical_xor()` retorna `True` se exatamente uma das afirmações for verdadeira.

Como é possível constatar, não temos diferenças nos valores de retorno entre os operadores lógicos nativos do Python e os do NumPy. Tanto que podemos utilizá-los sem discriminação para os casos habituais, isto é:

In [96]:
print(10 > 1 and 5 < 12) # Retorna True, pois 10 é maior do que 1 (True) e 5 é menor do que 12 (True).

True


In [97]:
print(np.logical_and(10 > 1, 5 < 12)) # Retorna True, pois 10 é maior do que 1 (True) e 5 é menor do que 12 (True).

True


Então qual seria o propósito de introduzir novos operadores com um funcionamento igual? Basicamente, abranger mais casos. Os operadores lógicos do NumPy são capazes de comparar, elemento por elemento, duas ndarrays de dimensões iguais (diferentemente dos nativos do Python). Vamos criar duas ndarrays com valores booleanos para demonstrar.

In [98]:
# Define L1: primeira coluna com valores True; segunda, com valores False.
L1 = np.array([[True, False], 
               [True, False]])

# Define L2: primeira linha com valores False; segunda, com valores True.
L2 = np.array([[False, False], 
               [True, True]])

***
**Observação:** como deve saber, não é necessário que os valores das ndarrays sejam booleanos, poderíamos, por exemplo, utilizar números (tendo em vista que, no Python, **0** é equivalente ao valor `False` e qualquer outro número, ao valor `True`).
***

In [99]:
print(np.logical_and(L1, L2)) # Retorna True onde L1 e L2 possuem True.

[[False False]
 [ True False]]


In [100]:
print(np.logical_or(L1, L2)) # Retorna True onde L1 ou L2 possuem True.

[[ True False]
 [ True  True]]


Além disso, uma última função importante é `np.where()`. Simplificadamente, passamos para ela uma condição e dois valores de retorno (chamaremos eles de `x` e `y`). Ela retornará `x` se a condição for verdadeira e `y` se a condição for falsa. Na prática, teremos:

In [101]:
print(np.where(B <= 5, "a", "b")) # condição=(B <= 5); x="a"; y="b".

[['a' 'a' 'a']
 ['a' 'a' 'b']
 ['b' 'b' 'b']]


Como podemos ver, onde **B** é menor ou igual a 5 recebe `"a"`, onde não, recebe `"b"`.

# Funções randômicas

Daremos aqui alguns exemplos das funções pseudorrandômicas que citamos no início, mas essas, introduzidas pelo NumPy. Elas são implementadas através do módulo `numpy.random` e são úteis, por exemplo, para a criação de ndarrays. A vantagem (e certas vezes a desvantagem) de trabalharmos com os *pseudo-random numbers* reside, justamente, no fato deles não serem completamente aleatórios, logo, embora não identifiquemos um padrão entre os números, poderemos sempre "recriá-los". Desde já, recomendaremos:

* a [lista de funções randômicas](https://numpy.org/doc/1.14/reference/routines.random.html) do NumPy *(versão 1.14)*;
* a [página da documentação](https://numpy.org/doc/1.17/reference/random/index.html) para um aprofundamento sobre a geração de números pseudorrandômicos, se tiver interesse.

Antes da parte de exemplos, vamos explicar o uso de `np.ramdom.seed()`. Basicamente, ela que nos garante a reprodutibilidade dos resultados. Faremos abaixo uma comparação, começando sem o uso dessa função.

In [102]:
np.random.rand() # Retorna um float pseudoaleatório qualquer.

0.44902267485791125

In [103]:
np.random.rand() # Retorna um float pseudoaleatório qualquer.

0.9496339327345853

A cada vez que as duas células a cima são executadas, a saída de cada uma é número qualquer. Contudo, se passarmos um inteiro (ou um `array_like` unidimensional) para `np.random.seed()` estaremos forçando sempre uma saída idêntica para as funções randômicas subsequentes. Podemos ver isso executando o código abaixo repetidas vezes.

In [104]:
np.random.seed(0) # Torna os números pseudoaletórios previsíveis.
np.random.rand()  # Retorna um float pseudoaleatório, agora, fixo.

0.5488135039273248

Dessa forma, é possível garantir, por exemplo, que nosso código seja executado sempre de uma mesma forma, ainda que trabalhe com funções randômicas. Por fim, temos nas construções abaixo outros casos.

In [105]:
# Retorna uma ndarray com 5 inteiros pertencentes ao intervalo [-10, 10).
print(np.random.randint(-10, 10, 5))

[-10  -7  -7  -3  -1]


In [106]:
# Retorna uma ndarray unidimensional com 3 elementos.
print(np.random.rand(3))

[0.6235637  0.38438171 0.29753461]


In [107]:
# Retorna uma matriz quadrada de ordem 2.
print(np.random.rand(2, 2))

[[0.05671298 0.27265629]
 [0.47766512 0.81216873]]


# Matemática e estatística

O NumPy introduz algumas dezenas de funções e expressões matemáticas além daquelas que já abordamos. Na verdade, a exemplo, temos casos em que podemos utilizar tanto `ndarray.sum()` para somar os elementos de uma ndarray (visto anteriormente), como também `np.sum()`. Como seria inviável (e desnecessário) apresentar cada uma delas, recomendamos fortemente consultar a [lista de funções matemáticas](https://numpy.org/doc/1.17/reference/routines.math.html) e de [estatística](https://numpy.org/doc/1.17/reference/routines.statistics.html) presentes na própria documentação da biblioteca. Nessas listas, além de separadas por categorias, as funções se encontram com uma breve explicação.

## *Mathematical functions*

A título de demonstração, trabalharemos alguns exemplos.

In [108]:
np.log(100) # Obtém o logarítimo natural de 100 (logarítimo de 100 na base e, sendo "e" o número de Euler).

4.605170185988092

In [109]:
np.log10(100) # Obtém o logarítimo decimal de 100 (logarítimo de 100 na base 10).

2.0

In [110]:
np.round_(np.log(100), 2) # Arredonda o logarítimo natural de 100 para a segunda casa decimal.

4.61

In [111]:
np.sqrt(4) # Raiz quadrada de 4

2.0

In [112]:
np.cbrt(27) # Raiz cúbica de 27

3.0

## Constantes

Outro ponto importante são as constantes que o NumPy introduz, na verdade, elas não são necessariamente matemáticas, como é possível verificar através da [relação de constantes](https://numpy.org/doc/1.17/reference/constants.html). Daremos atenção a três delas, começando por `np.pi`:

In [113]:
print(np.pi) # Constante matemática, razão entre o perímetro e o diâmetro de uma circunferência.

3.141592653589793


Seguindo para `np.e`:

In [114]:
print(np.e) # Constante matemática, o número de Euler.

2.718281828459045


E finalmente, `np.nan`, *Not a Number* (NaN):

In [115]:
print(np.nan) # Constante utilizada para indicar dados faltantes (missing data).

nan


## *Statistics*

Finalizando, vamos novamente exemplificar algumas funções úteis, dessa vez, para a determinação de dados estatísticos.

In [116]:
np.mean([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # A média de um array_like.

5.5

In [117]:
np.median([1, 2, 5, 9, 10]) # A mediana de um array_like.

5.0

In [118]:
np.std([1, 1, 3, 4, 5, 7, 7, 8, 9, 9, 10]) # O desvio padrão de um array_like.

3.0694441847516605

In [119]:
np.var([1, 1, 3, 4, 5, 7, 7, 8, 9, 9, 10]) # A variância de um array_like.

9.421487603305785

***

![Alt text](https://gistcdn.githack.com/Gbecdox/178a8d0cd024d5e52d63e3c11a2cdfd7/raw/3f32b8a31509ec3b2b20ebb202113b2da0e9c751/FooterGM.svg)
***